//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASIFICAR_ROPA
    {
        public int ID_CLASIFICACION { get; set; }
        public int CATEGORIA_NUMERO { get; set; }
        public string CATEGORIA_PRENDA { get; set; }
        public int CODIGO_PRODUCTO { get; set; }
    
        public virtual PRODUCTO_ROPA PRODUCTO_ROPA { get; set; }
    }
}
