//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_1_USUARIO { get; set; }
        public string APELLIDO_2_USUARIO { get; set; }
        public string TELEFONO_USUARIO { get; set; }
        public string CONTRASENNA { get; set; }
        public string TIPO_USUARIO { get; set; }
        public byte[] IMAGEN_USUARIO { get; set; }
    }
}
