CREATE DATABASE TIENDA_VIERNES
USE TIENDA_VIERNES

CREATE TABLE USUARIOS
(
	ID_USUARIO INT IDENTITY NOT NULL,
	CORREO_ELECTRONICO VARCHAR(50) PRIMARY KEY NOT NULL,
	NOMBRE_USUARIO VARCHAR(20) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO_1_USUARIO VARCHAR(20) NOT NULL,
	APELLIDO_2_USUARIO VARCHAR(20)NOT NULL,
	TELEFONO_USUARIO VARCHAR(20) NOT NULL, 
	CONTRASENNA VARCHAR(50) NOT NULL,
	TIPO_USUARIO VARCHAR(20) NOT NULL,
	IMAGEN_USUARIO VARBINARY(MAX)
)

CREATE TABLE METODO_PAGO
(
	NUMERO_TARJETA BIGINT PRIMARY KEY NOT NULL,
	NUMERO_EXPIRA_1 NUMERIC(2) NOT NULL,
	NUMERO_EXPIRA_2 NUMERIC(2) NOT NULL,
	CODIGO_TARJETA NUMERIC(3) NOT NULL,
	CORREO_ELECTRONICO VARCHAR(50) NOT NULL,
	TARJETA_ACTICA BIT NOT NULL,
	CONSTRAINT FK_USUARIO_TARJETA FOREIGN KEY (CORREO_ELECTRONICO) REFERENCES USUARIOS(CORREO_ELECTRONICO)
)

CREATE TABLE ADMINISTRADORES
(
	ID_USUARIO_ADMIN INT IDENTITY NOT NULL,
	CORREO_ELECTRONICO_ADMIN VARCHAR(50) PRIMARY KEY NOT NULL,
	NOMBRE_USUARIO_ADMIN VARCHAR(20) NOT NULL,
	NOMBRE_ADMIN VARCHAR(50) NOT NULL,
	APELLIDO_1_ADMIN VARCHAR(20) NOT NULL,
	APELLIDO_2_ADMIN VARCHAR(20)NOT NULL,
	TELEFONO_ADMIN VARCHAR(20) NOT NULL, 
	CONTRASENNA_ADMIN VARCHAR(50) NOT NULL,
	TIPO_USUARIO VARCHAR(20) NOT NULL
)

CREATE TABLE PRODUCTO_ROPA
(
	ID_PRODUCTO INT IDENTITY NOT NULL,
	CODIGO_PRODUCTO INT PRIMARY KEY NOT NULL,
	TIPO_PRENDA VARCHAR(100) NOT NULL,
	PRECIO_PRODUCTO INT NOT NULL,
	CANTIDAD_PRODUCTO INT NOT NULL,
	DESCRIPCION_PRODUCTO VARCHAR(2000) NOT NULL,
	TALLA_PRENDA VARCHAR(25) NOT NULL,
	IMAGEN VARBINARY(MAX) NOT NULL,
	MARCA VARCHAR(50) NOT NULL,
	PRODUCTO_ACTIVO BIT NOT NULL
)

CREATE TABLE CLASIFICAR_ROPA
(
	ID_CLASIFICACION INT IDENTITY PRIMARY KEY NOT NULL,
	CATEGORIA_NUMERO INT NOT NULL,
	CATEGORIA_PRENDA VARCHAR(100) NOT NULL,
	CODIGO_PRODUCTO INT NOT NULL,
	CONSTRAINT FK_PRENDA_CLASIFICAION FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO_ROPA(CODIGO_PRODUCTO)
)

CREATE TABLE CARRITO
(
	ID_CARRITO INT IDENTITY NOT NULL,
	NUMERO_CARRITO INT PRIMARY KEY NOT NULL,
	CORREO_ELECTRONICO VARCHAR(50) NOT NULL,
	CODIGO_PRODUCTO INT NOT NULL,
	CANTIDAD INT NOT NULL, 
	CARRITO_ACTIVO BIT NOT NULL,
	CONSTRAINT FK_CARRITO_USUARIO FOREIGN KEY (CORREO_ELECTRONICO) REFERENCES USUARIOS(CORREO_ELECTRONICO),
	CONSTRAINT FK_PRODUCTO_CARRITO FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO_ROPA(CODIGO_PRODUCTO)
)

CREATE TABLE GENERO_ROPA
(
	ID_GENERO INT IDENTITY PRIMARY KEY NOT NULL,
	GENERO_PRENDA VARCHAR(9) NOT NULL,
	NUMERO_GENERO INT NOT NULL,
	CODIGO_PRODUCTO INT NOT NULL,
	CONSTRAINT FK_PRENDA_GENERO FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO_ROPA(CODIGO_PRODUCTO)
)	

CREATE TABLE ORDER_COMPRA
(
	ID_ORDEN_COMPRA INT IDENTITY PRIMARY KEY NOT NULL,
	CORREO_ELECTRONICO VARCHAR(50) NOT NULL,
	NUMERO_TARJETA BIGINT NOT NULL,
	COMPRA_TOTAL INT NOT NULL,
	CONSTRAINT FK_ORDEN_COMPRA_USUARIO FOREIGN KEY (CORREO_ELECTRONICO) REFERENCES USUARIOS(CORREO_ELECTRONICO),
	CONSTRAINT FK_METODOPAGO_CARRITO FOREIGN KEY (NUMERO_TARJETA) REFERENCES METODO_PAGO(NUMERO_TARJETA),
)
