CREATE DATABASE TIENDA_VIERNES
USE TIENDA_VIERNES

CREATE TABLE USUARIOS
(
	ID_USUARIO INT IDENTITY NOT NULL,
	CORREO_ELECTRONICO VARCHAR(50) PRIMARY KEY NOT NULL,
	NOMBRE_USUARIO VARCHAR(20) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO_1_USUARIO VARCHAR(20) NOT NULL,
	APELLIDO_2_USUARIO VARCHAR(20)NOT NULL,
	TELEFONO_USUARIO VARCHAR(20) NOT NULL, 
	CONTRASENNA VARCHAR(50) NOT NULL,
	TIPO_USUARIO VARCHAR(20) NOT NULL
)

SELECT * FROM USUARIOS

CREATE TABLE ADMINISTRADORES
(
	ID_USUARIO_ADMIN INT IDENTITY NOT NULL,
	CORREO_ELECTRONICO_ADMIN VARCHAR(50) PRIMARY KEY NOT NULL,
	NOMBRE_USUARIO_ADMIN VARCHAR(20) NOT NULL,
	NOMBRE_ADMIN VARCHAR(50) NOT NULL,
	APELLIDO_1_ADMIN VARCHAR(20) NOT NULL,
	APELLIDO_2_ADMIN VARCHAR(20)NOT NULL,
	TELEFONO_ADMIN VARCHAR(20) NOT NULL, 
	CONTRASENNA_ADMIN VARCHAR(50) NOT NULL,
	TIPO_USUARIO VARCHAR(20) NOT NULL
)

SELECT * FROM ADMINISTRADORES

CREATE TABLE PRODUCTO_ROPA
(
	ID_PRODUCTO INT IDENTITY NOT NULL,
	CODIGO_PRODUCTO INT PRIMARY KEY NOT NULL,
	TIPO_PRENDA VARCHAR(100) NOT NULL,
	PRECIO_PRODUCTO INT NOT NULL,
	CANTIDAD_PRODUCTO INT NOT NULL,
	DESCRIPCION_PRODUCTO VARCHAR(2000) NOT NULL,
	TALLA_PRENDA VARCHAR(25) NOT NULL,
	IMAGEN VARBINARY(MAX) NOT NULL,
	MARCA VARCHAR(50) NOT NULL,
	PRODUCTO_ACTIVO BIT NOT NULL
)

SELECT * FROM PRODUCTO_ROPA

--CREATE TABLE PRODUCTO_ROPA
--(
--	ID_PRODUCTO INT IDENTITY NOT NULL,
--	CODIGO_PRODUCTO INT PRIMARY KEY NOT NULL,
--	NOMBRE_PRODUCTO VARCHAR(100) NOT NULL,
--	PRECIO_PRODUCTO INT NOT NULL,
--	CANTIDAD_PRODUCTO INT NOT NULL,
--	DESCRIPCION_PRODUCTO VARCHAR(2000) NOT NULL,
--	TIPO_PRODUCTO VARCHAR(25) NOT NULL,
--	IMAGEN VARBINARY(MAX) NOT NULL,
--	MARCA VARCHAR(50) NOT NULL,
--	PRODUCTO_ACTIVO BIT NOT NULL
--)



INSERT INTO ADMINISTRADORES
(
	CORREO_ELECTRONICO_ADMIN,
	NOMBRE_USUARIO_ADMIN,
	NOMBRE_ADMIN,
	APELLIDO_1_ADMIN,
	APELLIDO_2_ADMIN,
	TELEFONO_ADMIN, 
	CONTRASENNA_ADMIN,
	TIPO_USUARIO
)
VALUES
(
	'joselewis@gmail.com',
	'lewis',
	'José',
	'Gutiérrez',
	'Lewis',
	85344580,
	'12345',
	'Administrador'
)

