ALTER PROC SP_CARRITO_COMPRAS
@ID VARCHAR
AS
BEGIN
	SELECT COUNT(*)
	FROM PRODUCTO_ROPA
	INNER JOIN CARRITO ON CARRITO.CODIGO_PRODUCTO = PRODUCTO_ROPA.CODIGO_PRODUCTO
	INNER JOIN USUARIOS ON USUARIOS.CORREO_ELECTRONICO = CARRITO.CORREO_ELECTRONICO WHERE USUARIOS.CORREO_ELECTRONICO = 'joselewis@gmail.com'
END