INSERT INTO ORDEN_COMPRA
( 
	CORREO_ELECTRONICO,
	NUMERO_TARJETA, 
	COMPRA_TOTAL,
	CODIGO_PRODUCTO, 
	ID_CARRITO 
)
VALUES 
(
	'joselewis@gmail.com',
	12345678912365,
	140000,
	3061450,
	25
)

SELECT * FROM CARRITO WHERE CORREO_ELECTRONICO = 'joselewis@gmail.com'
SELECT * FROM METODO_PAGO WHERE CORREO_ELECTRONICO = 'joselewis@gmail.com'
SELECT * FROM PRODUCTO_ROPA