SELECT ID_ORDEN_COMPRA, NOMBRE, TIPO_PRENDA, COMPRA_TOTAL, CANTIDAD_PRODUCTO, CANTIDAD_DISPONIBLE
FROM USUARIOS
INNER JOIN METODO_PAGO ON METODO_PAGO.CORREO_ELECTRONICO =  USUARIOS.CORREO_ELECTRONICO 
INNER JOIN CARRITO ON CARRITO.CORREO_ELECTRONICO = USUARIOS.CORREO_ELECTRONICO 
INNER JOIN PRODUCTO_ROPA ON PRODUCTO_ROPA.CODIGO_PRODUCTO = CARRITO.CODIGO_PRODUCTO
INNER JOIN DINERO_PAGO ON DINERO_PAGO.NUMERO_TARJETA = METODO_PAGO.NUMERO_TARJETA
INNER JOIN ORDEN_COMPRA ON ORDEN_COMPRA.CORREO_ELECTRONICO = USUARIOS.CORREO_ELECTRONICO WHERE USUARIOS.CORREO_ELECTRONICO = 'joselewis@gmail.com'

SELECT * FROM METODO_PAGO WHERE CORREO_ELECTRONICO = 'joselewis@gmail.com'